### PR TITLE
Changed link protocol from http to https to account for mixed content error blocking

### PR DESCRIPTION
**Pull request by xtr33me**
The links referred to http but the page is https. This caused the ota links to be blocked from downloading due to a mixed content error. For verbosity, I was seeing this in Chrome 94.0.4606.71 on Mac 10.15.7

### CODE REVIEW

**Comment by bussardrobbie** [comment]
Hi @xtr33me,
Thanks for this PR! I was testing this and I think I found why this was left as HTTP. Vector cannot accept OTA update requests over HTTPS (part of why the Escape Pod is HTTP-only), and, at least on prod units and excepting where OSKR users have accepted alternate signing keys, relies on the signing key to be the source of truth for the security of the data transferred.

I tested this with the Vector-Web-Setup and you can see my results here:


May I ask you to modify your PR? Maybe what we can do here is leave the items that are SUPPOSED to be downloaded with a PC and stored (for use with updating via a Python server) as HTTPS links for browser compatibility, and maybe leave the nested commands as HTTP so that they work as copy/pasted, and perhaps a note that Vector does not support curling over HTTPS in all modes, so OTA update links must be served over HTTP?

If you'd rather, I can modify this to accommodate and pull in.

Thank you so much!
-Robbie

**Review by xtr33me — COMMENTED** [review]
MAde recommended changes regarding http and https. Now made direct clickable links that are meant to download the file directly https and left others.

**Comment by xtr33me** [comment]
Totally makes sense Robbie. Some changes reverted as requested. Sorry for the delayed response.

**Comment by bussardrobbie** [comment]
Hey @xtr33me, thanks for this! I'm pulling this into main and it should be deployed within 72 hours. I appreciate your contribution and feedback! Cheers.

**Pull request merged**
